# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoilerMake2020.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 624)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tree.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAccessibleName("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.lbTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbTitle.setFont(font)
        self.lbTitle.setObjectName("lbTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbTitle)
        self.lbAge = QtWidgets.QLabel(self.centralwidget)
        self.lbAge.setScaledContents(True)
        self.lbAge.setObjectName("lbAge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbAge)
        self.cbAge = QtWidgets.QComboBox(self.centralwidget)
        self.cbAge.setEnabled(True)
        self.cbAge.setObjectName("cbAge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbAge)
        self.lbEdu = QtWidgets.QLabel(self.centralwidget)
        self.lbEdu.setObjectName("lbEdu")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbEdu)
        self.cbEdu = QtWidgets.QComboBox(self.centralwidget)
        self.cbEdu.setObjectName("cbEdu")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbEdu)
        self.lbTravel1 = QtWidgets.QLabel(self.centralwidget)
        self.lbTravel1.setObjectName("lbTravel1")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbTravel1)
        self.chWalk = QtWidgets.QCheckBox(self.centralwidget)
        self.chWalk.setObjectName("chWalk")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.chWalk)
        self.lbTravel2 = QtWidgets.QLabel(self.centralwidget)
        self.lbTravel2.setObjectName("lbTravel2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbTravel2)
        self.chCar = QtWidgets.QCheckBox(self.centralwidget)
        self.chCar.setObjectName("chCar")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.chCar)
        self.chBus = QtWidgets.QCheckBox(self.centralwidget)
        self.chBus.setObjectName("chBus")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.chBus)
        self.chNone = QtWidgets.QCheckBox(self.centralwidget)
        self.chNone.setObjectName("chNone")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chNone)
        self.lbTime1 = QtWidgets.QLabel(self.centralwidget)
        self.lbTime1.setObjectName("lbTime1")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lbTime1)
        self.cbTime = QtWidgets.QComboBox(self.centralwidget)
        self.cbTime.setObjectName("cbTime")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.cbTime)
        self.lbTime2 = QtWidgets.QLabel(self.centralwidget)
        self.lbTime2.setObjectName("lbTime2")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lbTime2)
        self.lbEng1 = QtWidgets.QLabel(self.centralwidget)
        self.lbEng1.setObjectName("lbEng1")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.lbEng1)
        self.slEng = QtWidgets.QSlider(self.centralwidget)
        self.slEng.setMinimum(1)
        self.slEng.setMaximum(5)
        self.slEng.setOrientation(QtCore.Qt.Horizontal)
        self.slEng.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slEng.setTickInterval(1)
        self.slEng.setObjectName("slEng")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.slEng)
        self.lbEng2 = QtWidgets.QLabel(self.centralwidget)
        self.lbEng2.setObjectName("lbEng2")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.lbEng2)
        self.lbEng3 = QtWidgets.QLabel(self.centralwidget)
        self.lbEng3.setObjectName("lbEng3")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.lbEng3)
        self.lbKnow1 = QtWidgets.QLabel(self.centralwidget)
        self.lbKnow1.setObjectName("lbKnow1")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.lbKnow1)
        self.slKnow = QtWidgets.QSlider(self.centralwidget)
        self.slKnow.setMinimum(1)
        self.slKnow.setMaximum(5)
        self.slKnow.setOrientation(QtCore.Qt.Horizontal)
        self.slKnow.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slKnow.setTickInterval(1)
        self.slKnow.setObjectName("slKnow")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.slKnow)
        self.lbKnow2 = QtWidgets.QLabel(self.centralwidget)
        self.lbKnow2.setObjectName("lbKnow2")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.lbKnow2)
        self.lbKnow3 = QtWidgets.QLabel(self.centralwidget)
        self.lbKnow3.setObjectName("lbKnow3")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.lbKnow3)
        self.lbPrint1 = QtWidgets.QLabel(self.centralwidget)
        self.lbPrint1.setObjectName("lbPrint1")
        self.formLayout.setWidget(31, QtWidgets.QFormLayout.LabelRole, self.lbPrint1)
        self.lbPrint2 = QtWidgets.QLabel(self.centralwidget)
        self.lbPrint2.setObjectName("lbPrint2")
        self.formLayout.setWidget(32, QtWidgets.QFormLayout.LabelRole, self.lbPrint2)
        self.slPrint = QtWidgets.QSlider(self.centralwidget)
        self.slPrint.setMinimum(1)
        self.slPrint.setMaximum(5)
        self.slPrint.setOrientation(QtCore.Qt.Horizontal)
        self.slPrint.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slPrint.setTickInterval(1)
        self.slPrint.setObjectName("slPrint")
        self.formLayout.setWidget(31, QtWidgets.QFormLayout.FieldRole, self.slPrint)
        self.lbPrint3 = QtWidgets.QLabel(self.centralwidget)
        self.lbPrint3.setObjectName("lbPrint3")
        self.formLayout.setWidget(32, QtWidgets.QFormLayout.FieldRole, self.lbPrint3)
        self.lbTry1 = QtWidgets.QLabel(self.centralwidget)
        self.lbTry1.setObjectName("lbTry1")
        self.formLayout.setWidget(34, QtWidgets.QFormLayout.LabelRole, self.lbTry1)
        self.lbTry2 = QtWidgets.QLabel(self.centralwidget)
        self.lbTry2.setObjectName("lbTry2")
        self.formLayout.setWidget(35, QtWidgets.QFormLayout.LabelRole, self.lbTry2)
        self.lbTry3 = QtWidgets.QLabel(self.centralwidget)
        self.lbTry3.setObjectName("lbTry3")
        self.formLayout.setWidget(36, QtWidgets.QFormLayout.LabelRole, self.lbTry3)
        self.chTry1 = QtWidgets.QCheckBox(self.centralwidget)
        self.chTry1.setObjectName("chTry1")
        self.formLayout.setWidget(34, QtWidgets.QFormLayout.FieldRole, self.chTry1)
        self.chTry2 = QtWidgets.QCheckBox(self.centralwidget)
        self.chTry2.setObjectName("chTry2")
        self.formLayout.setWidget(35, QtWidgets.QFormLayout.FieldRole, self.chTry2)
        self.chTry3 = QtWidgets.QCheckBox(self.centralwidget)
        self.chTry3.setObjectName("chTry3")
        self.formLayout.setWidget(36, QtWidgets.QFormLayout.FieldRole, self.chTry3)
        self.chTry4 = QtWidgets.QCheckBox(self.centralwidget)
        self.chTry4.setObjectName("chTry4")
        self.formLayout.setWidget(37, QtWidgets.QFormLayout.FieldRole, self.chTry4)
        self.chTry5 = QtWidgets.QCheckBox(self.centralwidget)
        self.chTry5.setObjectName("chTry5")
        self.formLayout.setWidget(38, QtWidgets.QFormLayout.FieldRole, self.chTry5)
        self.cbOthers = QtWidgets.QComboBox(self.centralwidget)
        self.cbOthers.setObjectName("cbOthers")
        self.formLayout.setWidget(39, QtWidgets.QFormLayout.FieldRole, self.cbOthers)
        self.lbOthers1 = QtWidgets.QLabel(self.centralwidget)
        self.lbOthers1.setObjectName("lbOthers1")
        self.formLayout.setWidget(39, QtWidgets.QFormLayout.LabelRole, self.lbOthers1)
        self.lbOthers2 = QtWidgets.QLabel(self.centralwidget)
        self.lbOthers2.setObjectName("lbOthers2")
        self.formLayout.setWidget(40, QtWidgets.QFormLayout.LabelRole, self.lbOthers2)
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit.setObjectName("btnSubmit")
        self.formLayout.setWidget(41, QtWidgets.QFormLayout.LabelRole, self.btnSubmit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Carbon Footprint Predictor"))
        self.lbTitle.setText(_translate("MainWindow", "Answer the questions below!"))
        self.lbAge.setText(_translate("MainWindow", "Age Range"))
        self.lbEdu.setText(_translate("MainWindow", "Education Status"))
        self.lbTravel1.setText(_translate("MainWindow", "How do you travel to work/university?"))
        self.chWalk.setText(_translate("MainWindow", "Walk/cycle"))
        self.lbTravel2.setText(_translate("MainWindow", "(choose all that apply)"))
        self.chCar.setText(_translate("MainWindow", "Car/motorbike"))
        self.chBus.setText(_translate("MainWindow", "Bus/Train"))
        self.chNone.setText(_translate("MainWindow", "I don\'t travel"))
        self.lbTime1.setText(_translate("MainWindow", "On average, how long does it take you"))
        self.lbTime2.setText(_translate("MainWindow", "to travel to university?"))
        self.lbEng1.setText(_translate("MainWindow", "How engaged do you feel with the"))
        self.lbEng2.setText(_translate("MainWindow", "issue of climate change?"))
        self.lbEng3.setText(_translate("MainWindow", "1 - Not very engaged to 5 - Very engaged"))
        self.lbKnow1.setText(_translate("MainWindow", "Do you know what your carbon"))
        self.lbKnow2.setText(_translate("MainWindow", "footprint is?"))
        self.lbKnow3.setText(_translate("MainWindow", "1 - Not very aware to 5 - Very aware"))
        self.lbPrint1.setText(_translate("MainWindow", "How would you rate your carbon"))
        self.lbPrint2.setText(_translate("MainWindow", "footprint?"))
        self.lbPrint3.setText(_translate("MainWindow", "1 - Very bad to 5 - Very good"))
        self.lbTry1.setText(_translate("MainWindow", "How have you tried to reduce your"))
        self.lbTry2.setText(_translate("MainWindow", "carbon footprint?"))
        self.lbTry3.setText(_translate("MainWindow", "(choose 1-3 options)"))
        self.chTry1.setText(_translate("MainWindow", "I have changed how I travel"))
        self.chTry2.setText(_translate("MainWindow", "I have changed what I eat"))
        self.chTry3.setText(_translate("MainWindow", "I have changed my devices or appliances in my house"))
        self.chTry4.setText(_translate("MainWindow", "I have changed my gas or electricity supplier"))
        self.chTry5.setText(_translate("MainWindow", "I have not tried to reduce my carbon footprint"))
        self.lbOthers1.setText(_translate("MainWindow", "Have you tried to encourage others"))
        self.lbOthers2.setText(_translate("MainWindow", "to reduce their carbon footprint?"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
