# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoilerMake2020.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 624)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tree.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAccessibleName("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbKnow1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbKnow1.setFont(font)
        self.lbKnow1.setObjectName("lbKnow1")
        self.gridLayout.addWidget(self.lbKnow1, 39, 1, 1, 1)
        self.slKnow = QtWidgets.QSlider(self.centralwidget)
        self.slKnow.setMinimum(1)
        self.slKnow.setMaximum(5)
        self.slKnow.setOrientation(QtCore.Qt.Horizontal)
        self.slKnow.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slKnow.setTickInterval(1)
        self.slKnow.setObjectName("slKnow")
        self.gridLayout.addWidget(self.slKnow, 39, 2, 1, 1)
        self.lbTime2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTime2.setFont(font)
        self.lbTime2.setObjectName("lbTime2")
        self.gridLayout.addWidget(self.lbTime2, 32, 1, 1, 1)
        self.slPrint = QtWidgets.QSlider(self.centralwidget)
        self.slPrint.setMinimum(1)
        self.slPrint.setMaximum(5)
        self.slPrint.setOrientation(QtCore.Qt.Horizontal)
        self.slPrint.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slPrint.setTickInterval(1)
        self.slPrint.setObjectName("slPrint")
        self.gridLayout.addWidget(self.slPrint, 42, 2, 1, 1)
        self.lbTry3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTry3.setFont(font)
        self.lbTry3.setObjectName("lbTry3")
        self.gridLayout.addWidget(self.lbTry3, 47, 1, 1, 1)
        self.lbTravel1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTravel1.setFont(font)
        self.lbTravel1.setObjectName("lbTravel1")
        self.gridLayout.addWidget(self.lbTravel1, 11, 1, 1, 1)
        self.lbEng2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbEng2.setFont(font)
        self.lbEng2.setObjectName("lbEng2")
        self.gridLayout.addWidget(self.lbEng2, 35, 1, 1, 1)
        self.lbEng3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbEng3.setFont(font)
        self.lbEng3.setObjectName("lbEng3")
        self.gridLayout.addWidget(self.lbEng3, 35, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 41, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 33, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 44, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 50, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 54, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 38, 1, 1, 1)
        self.lbAge = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbAge.setFont(font)
        self.lbAge.setScaledContents(True)
        self.lbAge.setObjectName("lbAge")
        self.gridLayout.addWidget(self.lbAge, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 6, 2, 1, 1)
        self.chWalk = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chWalk.setFont(font)
        self.chWalk.setObjectName("chWalk")
        self.gridLayout.addWidget(self.chWalk, 14, 2, 1, 1)
        self.chNone = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chNone.setFont(font)
        self.chNone.setObjectName("chNone")
        self.gridLayout.addWidget(self.chNone, 15, 2, 1, 1)
        self.chCar = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chCar.setFont(font)
        self.chCar.setObjectName("chCar")
        self.gridLayout.addWidget(self.chCar, 11, 2, 1, 1)
        self.lbWork = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbWork.setFont(font)
        self.lbWork.setObjectName("lbWork")
        self.gridLayout.addWidget(self.lbWork, 7, 1, 1, 1)
        self.cbWork = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbWork.setFont(font)
        self.cbWork.setObjectName("cbWork")
        self.gridLayout.addWidget(self.cbWork, 7, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 8, 1, 1, 1)
        self.cbTime = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbTime.setFont(font)
        self.cbTime.setObjectName("cbTime")
        self.gridLayout.addWidget(self.cbTime, 31, 2, 1, 1)
        self.lbEng1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbEng1.setFont(font)
        self.lbEng1.setObjectName("lbEng1")
        self.gridLayout.addWidget(self.lbEng1, 34, 1, 1, 1)
        self.chTry2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chTry2.setFont(font)
        self.chTry2.setObjectName("chTry2")
        self.gridLayout.addWidget(self.chTry2, 46, 2, 1, 1)
        self.lbTry2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTry2.setFont(font)
        self.lbTry2.setObjectName("lbTry2")
        self.gridLayout.addWidget(self.lbTry2, 46, 1, 1, 1)
        self.lbKnow3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbKnow3.setFont(font)
        self.lbKnow3.setObjectName("lbKnow3")
        self.gridLayout.addWidget(self.lbKnow3, 40, 2, 1, 1)
        self.lbPrint2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbPrint2.setFont(font)
        self.lbPrint2.setObjectName("lbPrint2")
        self.gridLayout.addWidget(self.lbPrint2, 43, 1, 1, 1)
        self.lbKnow2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbKnow2.setFont(font)
        self.lbKnow2.setObjectName("lbKnow2")
        self.gridLayout.addWidget(self.lbKnow2, 40, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 4, 1, 1, 1)
        self.lbTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lbTitle.setFont(font)
        self.lbTitle.setObjectName("lbTitle")
        self.gridLayout.addWidget(self.lbTitle, 0, 1, 1, 2)
        self.lbTime1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTime1.setFont(font)
        self.lbTime1.setObjectName("lbTime1")
        self.gridLayout.addWidget(self.lbTime1, 31, 1, 1, 1)
        self.slEng = QtWidgets.QSlider(self.centralwidget)
        self.slEng.setMinimum(1)
        self.slEng.setMaximum(5)
        self.slEng.setOrientation(QtCore.Qt.Horizontal)
        self.slEng.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slEng.setTickInterval(1)
        self.slEng.setObjectName("slEng")
        self.gridLayout.addWidget(self.slEng, 34, 2, 1, 1)
        self.lbPrint3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbPrint3.setFont(font)
        self.lbPrint3.setObjectName("lbPrint3")
        self.gridLayout.addWidget(self.lbPrint3, 43, 2, 1, 1)
        self.lbTravel2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTravel2.setFont(font)
        self.lbTravel2.setObjectName("lbTravel2")
        self.gridLayout.addWidget(self.lbTravel2, 12, 1, 1, 1)
        self.lbEdu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbEdu.setFont(font)
        self.lbEdu.setObjectName("lbEdu")
        self.gridLayout.addWidget(self.lbEdu, 5, 1, 1, 1)
        self.cbEdu = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbEdu.setFont(font)
        self.cbEdu.setObjectName("cbEdu")
        self.gridLayout.addWidget(self.cbEdu, 5, 2, 1, 1)
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.gridLayout.addWidget(self.btnSubmit, 56, 1, 1, 1)
        self.lbYou = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbYou.setFont(font)
        self.lbYou.setObjectName("lbYou")
        self.gridLayout.addWidget(self.lbYou, 37, 1, 1, 1)
        self.lbOthers2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbOthers2.setFont(font)
        self.lbOthers2.setObjectName("lbOthers2")
        self.gridLayout.addWidget(self.lbOthers2, 53, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 3, 1, 1)
        self.cbAge = QtWidgets.QComboBox(self.centralwidget)
        self.cbAge.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbAge.setFont(font)
        self.cbAge.setObjectName("cbAge")
        self.gridLayout.addWidget(self.cbAge, 2, 2, 1, 1)
        self.chTry1 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chTry1.setFont(font)
        self.chTry1.setObjectName("chTry1")
        self.gridLayout.addWidget(self.chTry1, 45, 2, 1, 1)
        self.lbTry1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbTry1.setFont(font)
        self.lbTry1.setObjectName("lbTry1")
        self.gridLayout.addWidget(self.lbTry1, 45, 1, 1, 1)
        self.lbPrint1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbPrint1.setFont(font)
        self.lbPrint1.setObjectName("lbPrint1")
        self.gridLayout.addWidget(self.lbPrint1, 42, 1, 1, 1)
        self.chTry3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chTry3.setFont(font)
        self.chTry3.setObjectName("chTry3")
        self.gridLayout.addWidget(self.chTry3, 47, 2, 1, 1)
        self.lbOthers1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lbOthers1.setFont(font)
        self.lbOthers1.setObjectName("lbOthers1")
        self.gridLayout.addWidget(self.lbOthers1, 52, 1, 1, 1)
        self.chBus = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chBus.setFont(font)
        self.chBus.setObjectName("chBus")
        self.gridLayout.addWidget(self.chBus, 12, 2, 1, 1)
        self.chTry4 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chTry4.setFont(font)
        self.chTry4.setObjectName("chTry4")
        self.gridLayout.addWidget(self.chTry4, 48, 2, 1, 1)
        self.chTry5 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.chTry5.setFont(font)
        self.chTry5.setObjectName("chTry5")
        self.gridLayout.addWidget(self.chTry5, 49, 2, 1, 1)
        self.cbOthers = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbOthers.setFont(font)
        self.cbOthers.setObjectName("cbOthers")
        self.gridLayout.addWidget(self.cbOthers, 52, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 30, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 1, 1, 1, 1)
        self.cbYou = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.cbYou.setFont(font)
        self.cbYou.setObjectName("cbYou")
        self.gridLayout.addWidget(self.cbYou, 37, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 36, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Carbon Footprint Predictor"))
        self.lbKnow1.setText(_translate("MainWindow", "Do you know what your carbon"))
        self.lbTime2.setText(_translate("MainWindow", "to travel to university?"))
        self.lbTry3.setText(_translate("MainWindow", "(choose 1-3 options)"))
        self.lbTravel1.setText(_translate("MainWindow", "How do you travel to work/university?    "))
        self.lbEng2.setText(_translate("MainWindow", "issue of climate change?"))
        self.lbEng3.setText(_translate("MainWindow", "1 - Not very engaged to 5 - Very engaged"))
        self.lbAge.setText(_translate("MainWindow", "Age Range"))
        self.chWalk.setText(_translate("MainWindow", "Walk/cycle"))
        self.chNone.setText(_translate("MainWindow", "I don\'t travel"))
        self.chCar.setText(_translate("MainWindow", "Car/motorbike"))
        self.lbWork.setText(_translate("MainWindow", "Work Status"))
        self.lbEng1.setText(_translate("MainWindow", "How engaged do you feel with the"))
        self.chTry2.setText(_translate("MainWindow", "I have changed what I eat"))
        self.lbTry2.setText(_translate("MainWindow", "carbon footprint?"))
        self.lbKnow3.setText(_translate("MainWindow", "1 - Not very aware to 5 - Very aware"))
        self.lbPrint2.setText(_translate("MainWindow", "footprint?"))
        self.lbKnow2.setText(_translate("MainWindow", "footprint is?"))
        self.lbTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; text-decoration: underline; color:#55aa00;\">College Student Carbon Footprint Predictor</span></p></body></html>"))
        self.lbTime1.setText(_translate("MainWindow", "On average, how long does it take you"))
        self.lbPrint3.setText(_translate("MainWindow", "1 - Very bad to 5 - Very good"))
        self.lbTravel2.setText(_translate("MainWindow", "(choose all that apply)"))
        self.lbEdu.setText(_translate("MainWindow", "Education Status"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))
        self.lbYou.setText(_translate("MainWindow", "Do you know what a carbon footprint is?"))
        self.lbOthers2.setText(_translate("MainWindow", "to reduce their carbon footprint?"))
        self.chTry1.setText(_translate("MainWindow", "I have changed how I travel"))
        self.lbTry1.setText(_translate("MainWindow", "How have you tried to reduce your"))
        self.lbPrint1.setText(_translate("MainWindow", "How would you rate your carbon"))
        self.chTry3.setText(_translate("MainWindow", "I have changed my devices or appliances in my house"))
        self.lbOthers1.setText(_translate("MainWindow", "Have you tried to encourage others"))
        self.chBus.setText(_translate("MainWindow", "Bus/Train"))
        self.chTry4.setText(_translate("MainWindow", "I have changed my gas or electricity supplier"))
        self.chTry5.setText(_translate("MainWindow", "I have not tried to reduce my carbon footprint"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
