# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CarbonFootprint.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow2(object):
    def setupUi(self, mainWindow2):
        mainWindow2.setObjectName("mainWindow2")
        mainWindow2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCalc = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.btnCalc.setFont(font)
        self.btnCalc.setObjectName("btnCalc")
        self.gridLayout.addWidget(self.btnCalc, 7, 1, 1, 1)
        self.leDrive = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.leDrive.setFont(font)
        self.leDrive.setObjectName("leDrive")
        self.gridLayout.addWidget(self.leDrive, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.lbTitle2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.lbTitle2.setFont(font)
        self.lbTitle2.setObjectName("lbTitle2")
        self.gridLayout.addWidget(self.lbTitle2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.leShop = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.leShop.setFont(font)
        self.leShop.setObjectName("leShop")
        self.gridLayout.addWidget(self.leShop, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.lePlane = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lePlane.setFont(font)
        self.lePlane.setObjectName("lePlane")
        self.gridLayout.addWidget(self.lePlane, 4, 2, 1, 1)
        self.leBeef = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.leBeef.setFont(font)
        self.leBeef.setObjectName("leBeef")
        self.gridLayout.addWidget(self.leBeef, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.btnNext.setFont(font)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 9, 1, 1, 1)
        self.leFoot = QtWidgets.QLineEdit(self.centralwidget)
        self.leFoot.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.leFoot.setFont(font)
        self.leFoot.setObjectName("leFoot")
        self.gridLayout.addWidget(self.leFoot, 7, 2, 1, 1)
        mainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        mainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow2)
        self.statusbar.setObjectName("statusbar")
        mainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow2)

    def retranslateUi(self, mainWindow2):
        _translate = QtCore.QCoreApplication.translate
        mainWindow2.setWindowTitle(_translate("mainWindow2", "Carbon Footprint Calculator"))
        self.btnCalc.setText(_translate("mainWindow2", "Calculate My Carbon Footprint!"))
        self.lbTitle2.setText(_translate("mainWindow2", "<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline; color:#55aa00;\">Carbon Footprint Calculator</span></p></body></html>"))
        self.label_4.setText(_translate("mainWindow2", "Enter how many times you shop (grocery plus clothing) in a week:"))
        self.label_2.setText(_translate("mainWindow2", "Enter how many hours you spend on a plane per year:"))
        self.label.setText(_translate("mainWindow2", "Enter how many miles you drive per week:"))
        self.label_3.setText(_translate("mainWindow2", "Enter how many servings of beef you eat per week:"))
        self.btnNext.setText(_translate("mainWindow2", "Next >"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_mainWindow2()
    ui.setupUi(mainWindow2)
    mainWindow2.show()
    sys.exit(app.exec_())
